apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: team-innbygger-dokumentasjon
  namespace: aap
  labels:
    team: aap
spec:
  port: 8080
  ingresses:
    - https://aap-team-innbygger.intern.nav.no
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
  liveness:
    path: /internal/isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /internal/isready
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false