@startuml
entity RettighetsPeriode {
  fraDato: date
  tilDato: date
  rettighetstype: string
}

entity "behandlinger" as behandlinger {
        saksnummer: string
        behandlingsreferanse: string
        behandlingsType: string
        brukerFnr: string
        datoAvsluttet: date
        kodeverk: string | null
        diagnosekode: string | null
        bidiagnoser: string[] | null
        rettighetsPerioder: RettighetsPeriode[]
        radEndret: datetime
        utbetalingId: string
        resultat: string | null
}

entity "beregningsgrunnlag" {
saksnummer: string
behandlingsreferanse: string
}

entity "tilkjentYtelse" {
saksnummer: string
behandlingsreferanse: string
}

entity "vilkarsResultat" {
saksnummer: string
behandlingsreferanse: string
}

behandlinger  -->  beregningsgrunnlag : "referanse : behandlingsreferanse"
behandlinger  -->  tilkjentYtelse : "referanse : behandlingsreferanse"
behandlinger  -->  vilkarsResultat : "referanse : behandlingsreferanse"
behandlinger o-- RettighetsPeriode
@enduml
