@startuml

entity "tilkjentYtelse" {
        saksnummer: text
        behandlingsreferanse: text
        fra_dato: date
        til_dato: date
        dagsats: float64
        gradering: float64
        antall_barn: int64
        barnetillegg: float64
        barnetillegg_sats: float64
        redusert_dagsats: float64
        reg_dato: date
        endret_tid: date
        unik_id: long
}
@enduml
